apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: r-glmm-plumber
  namespace: seedtest
  labels:
    app: r-glmm-plumber
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: r-glmm-plumber
  endpoints:
  - port: http
    path: /healthz
    interval: 30s
    scrapeTimeout: 10s

