apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: portal-frontend-pdb
  namespace: seedtest
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: portal-frontend
