apiVersion: v1
kind: Service
metadata:
  name: portal-frontend
  namespace: seedtest
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: portal-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
