apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: seedtest-db-credentials
  namespace: seedtest
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: seedtest-db-credentials
    template:
      type: Opaque
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        # Change this to match your GSM secret name that contains the full Postgres connection URL
        key: seedtest-staging-database-url
