# cSpell:ignore externalsecrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: r-analytics-credentials
  namespace: seedtest
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore  # Namespace-scoped SecretStore
  target:
    name: r-analytics-credentials
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: r-analytics-internal-token
