apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: seedtest-api-pdb
  namespace: seedtest
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seedtest-api
