apiVersion: v1
kind: Service
metadata:
  name: seedtest-api
  namespace: seedtest
  labels:
    app.kubernetes.io/name: seedtest-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: seedtest-api
  ports:
    - name: http
      port: 80
      targetPort: http
