apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: r-glmm-plumber
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: r-glmm-plumber
  namespaceSelector:
    matchNames:
      - seedtest
  endpoints:
    - port: http
      path: /healthz
      interval: 30s
