apiVersion: v1
kind: ResourceQuota
metadata:
  name: seedtest-quota
  namespace: seedtest
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "80"
    services: "30"
    configmaps: "50"
    secrets: "100"
