# SecretStore for Google Cloud Secret Manager (GCP)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  namespace: seedtest
spec:
  provider:
    gcpsm:
      projectID: univprepai
      auth:
        workloadIdentity:
          # The KSA used by ExternalSecrets to fetch secrets via GCP Workload Identity
          serviceAccountRef:
            name: seedtest-api
