apiVersion: v1
kind: Service
metadata:
  name: seedtest-api
  namespace: seedtest
  labels:
    app: seedtest-api
    governance: enabled
spec:
  selector:
    app: seedtest-api
  ports:
    - name: http
      port: 8000          # ClusterIP 서비스 포트
      targetPort: 8000    # 컨테이너 포트
      protocol: TCP
  type: ClusterIP
