apiVersion: v1
kind: Service
metadata:
  name: r-brms-plumber
  namespace: seedtest
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: r-brms-plumber
  ports:
    - name: http
      port: 80
      targetPort: http
