apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: r-irt-credentials
  namespace: seedtest
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: r-irt-credentials
  data:
    - secretKey: token
      remoteRef:
        key: r-irt-internal-token
